# initialize display of M5 dial
# will be extended by page packages 

display:
  - platform: gc9a01
    reset_pin: GPIO8
    cs_pin: GPIO7
    dc_pin: GPIO4
    rotation: 90
    update_interval: 1h
    id: touchscreen_lcd
    

sensor:
  - platform: rotary_encoder
    id: touchscreen_rotary
    internal: true
    pin_a: 
      number: GPIO40
      mode:
       input: true
       pullup: true
    pin_b: 
      number: GPIO41
      mode:
       input: true
       pullup: true
    accuracy_decimals: 0
    on_value: 
      - then:
        - script.execute:
            id: touchscreen_display_set_countdown

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time: 
      - seconds: /1
        then:
          - if:
              condition:
                - number.in_range:
                    id: touchscreen_display_countdown
                    above: 1
              then:
                - number.decrement:
                    id: touchscreen_display_countdown
                    cycle: false
          - if:
              condition:
                - number.in_range:
                    id: touchscreen_button_freeze_countdown
                    above: 1
              then:
                - number.decrement:
                    id: touchscreen_button_freeze_countdown
                    cycle: false