esphome:
  name: quti-dial
  friendly_name: QuTi-dial

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "0QpNMKvxJmHLCCuHXw1OLeruMW2bv1Xw3l5RwAw3pBw="
  on_client_connected:
    then:
    - display.page.show: clockpage
    - script.execute: 
        id: touchscreen_display_set_countdown 

ota:
  password: "e9228a94b88ae00110e92f7959ec69b1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Quti-Dial Fallback Hotspot"
    password: "byVv0XBR9BXk"

captive_portal:
    

# yaml was mainly copied from Squall290586 from here
# https://community.home-assistant.io/t/m5stack-dial-esp32-s3-smart-rotary-knob/623518/119 
# and then adapted to my needs (packages, colors, functionality) 

# spi for display
spi:
  mosi_pin: GPIO5
  clk_pin: GPIO6

i2c:
    # setup i2c with id bus_internal for touchscreen
  - id: bus_internal
    sda: GPIO11
    scl: GPIO12
  #- id: bus_porta
  #  sda: 13
  #  scl: 15

external_components:
  - source: github://dgaust/esphome@gc9a01
    components: [ gc9a01, ft3267 ]
    refresh: 0s    

# include packages to display pages
packages:
  #always include display first, then add pages. 
  display: !include quti_dial/display.yaml
  clockpage: !include quti_dial/clock.yaml

  #pages are cycled in order they are defined here
  your_light_1: !include
    file: quti_dial/page_light.yaml
    vars:
      my_name: "wozi3"
      my_entity: "light.wozi_3"
      my_image: "mdi:lightbulb"

  your_climate_1: !include 
    file: quti_dial/page_climate.yaml
    vars:
      my_name: "climate2"
      my_entity: "climate.heizung_truma_room"
  
  your_light_2: !include
    file: quti_dial/page_light.yaml
    vars:
      my_name: "wozi1"
      my_entity: "light.wozi_1"
      my_image: "mdi:fan"

  your_media_media1: !include
    file: quti_dial/page_media.yaml
    vars:
      my_name: "Feel_the_bass"
      my_entity: "media_player.ad8eacf5_9d58ec77"
         
 
