# yaml was mainly copied from Squall290586 from here
# https://community.home-assistant.io/t/m5stack-dial-esp32-s3-smart-rotary-knob/623518/119 
# and then adapted to my needs (packages, colors, functionality) 

esphome:
  name: rotary-test
  friendly_name: rotary_test
  

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
   level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "OPSqVGQ6XPVEkarePrt8IFRLBrCf/zbPMWOePH9AKps="

ota:
  password: "2abedc7a9138fab45d13bf7da07af14c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rotary-Test Fallback Hotspot"
    password: "zAbXK6NqAGhw"

captive_portal:

# spi for display
spi:
  mosi_pin: GPIO5
  clk_pin: GPIO6

i2c:
    # setup i2c with id bus_internal for touchscreen
  - id: bus_internal
    sda: GPIO11
    scl: GPIO12
  - id: bus_porta
    sda: 13
    scl: 15

external_components:
  - source: github://dgaust/esphome@gc9a01
    components: [ gc9a01, ft3267 ]
    refresh: 0s    

# include packages to display pages
packages:
  #always include display first, then add pages. 
  display: !include display.yaml

  #pages are cycled in order they are defined here
  wozi_light4: !include
    file: page_light.yaml   
    vars:
      my_name: "wozi4"
      my_entity: "light.wozi_4"
      my_image: "mdi:lightbulb"

  climate_2: !include 
    file: page_climate.yaml    
    vars:
      my_name: "climate2"
      my_entity: "climate.heizung_truma_room"
  
  wozi_light1: !include
    file: page_light.yaml
    vars:
      my_name: "wozi1"
      my_entity: "light.wozi_1"
      my_image: "mdi:fan"

  climate_1: !include 
    file: page_climate.yaml
    vars:
      my_name: "climate"
      my_entity: "climate.heizung_truma_water"
      step: "40"      
