#define defaults that are used if no value is given

defaults: 
  my_play: mdi:play
  my_pause: mdi:pause

#define images and colors 
image:
  - file: ${my_play}
    id: play_icon_${my_name}
    resize: 100x100
  - file: ${my_pause}
    id: pause_icon_${my_name}
    resize: 100x100    

#define sensors
#make sure to define
# sensors that provide actual state (platform home assistant)    
# 

sensor:
  - platform: rotary_encoder
    id: !extend touchscreen_rotary
    on_clockwise: 
      then:
          - if:
              condition:
                display.is_displaying_page: ${my_name}
              then:
                - script.execute:
                    id: volume_up_script_${my_name}
    on_anticlockwise: 
      then:
          - if:
              condition:
                display.is_displaying_page: ${my_name}
              then:
                - script.execute:
                    id: volume_down_script_${my_name}   

  - platform: homeassistant
    id: volume_${my_name}
    entity_id: $my_entity
    attribute: volume_level
    filters:
      - multiply: 100    

    on_value:
      then:
        - logger.log: "new volume from HA"
        - lambda: !lambda |-
              id(new_volume_${my_name}).publish_state(id(volume_${my_name}).state);
        - component.update: touchscreen_lcd

# define touchscreen areas
binary_sensor:
  - platform: touchscreen
    id: play_toggle_touchscreen_button_${my_name}
    internal: true
    x_min: 75
    x_max: 175
    y_min: 75
    y_max: 175
    page_id: ${my_name}
    on_state: 
      then:
        - script.execute:
            id: play_toggle_script_${my_name}

  - platform: template
    id: play_pause_binary_${my_name}
    internal: True

          
text_sensor:
  - platform: homeassistant
    id: play_switch_${my_name}
    entity_id: ${my_entity}
    on_value:
      then:
        - component.update: touchscreen_lcd  

number:
  # Public
  - platform: template
    id: new_volume_${my_name}
    name: Volume_${my_name}
    icon: mdi:speaker
    optimistic: true
    min_value: 0
    max_value: 100
    step: 5
    initial_value: 10


#define script on how to react on touches
script:
  - id: play_toggle_script_${my_name}
    mode: single
    then:
      - if:
          condition:
            - lambda: |-
                return id(touchscreen_display_on).state;
          then:
            - homeassistant.service:
                service: media_player.media_play_pause
                data:
                  entity_id: ${my_entity}
            - logger.log: "Toggle! ${my_name}"
            - delay: 500ms

    #set new temperature
  - id: apply_new_volume_${my_name}
    mode: single
    then:
      - logger.log: "send set volume"
      - delay: 500ms
      - if:
          condition:
            - lambda: |-
                return id(touchscreen_display_on).state && id(new_volume_${my_name}).state >= 0 && id(new_volume_${my_name}).state <= 100;
          then:
            - logger.log: "send to HA"
            - homeassistant.service:
                service: media_player.volume_set
                data:
                  entity_id: ${my_entity}
                  volume_level: !lambda |-
                    return id(new_volume_${my_name}).state / 100;
       
    #set brightness up one step   
  - id: volume_up_script_${my_name}
    mode: single
    then:
      - if:
          #if display is on
          condition:
            - lambda: |-
                return id(touchscreen_display_on).state;
          then:
            #up one step
            - lambda: |-
                return id(new_volume_${my_name}).publish_state(id(new_volume_${my_name}).state + 5);
            #if new brightness is already at max stay with max
            - lambda: |-
                return id(new_volume_${my_name}).publish_state((id(new_volume_${my_name}).state < 100) ? id(new_volume_${my_name}).state : 100);
            - script.execute:
                id: apply_new_volume_${my_name}
            - component.update: touchscreen_lcd

    #set brightness down one step
  - id: volume_down_script_${my_name}
    mode: single
    then:
      - if:
          #if display is on      
          condition:
            - lambda: |-
                return id(touchscreen_display_on).state;
          then:
            #up one step                
            - lambda: |-
                return id(new_volume_${my_name}).publish_state(id(new_volume_${my_name}).state - 5);
            #if new brightness is already at min stay with min
            - lambda: |-
                return id(new_volume_${my_name}).publish_state((id(new_volume_${my_name}).state > 0) ? id(new_volume_${my_name}).state : 0);
            - script.execute:
                id: apply_new_volume_${my_name}                
            - component.update: touchscreen_lcd



#define display page            
display:
  - platform: gc9a01
    id: !extend touchscreen_lcd

    pages:
      - id: ${my_name}
        lambda: |-
          // Variables
          float screenheight = it.get_height();
          float screenwidth = it.get_width();
          float halfscreenheight = screenheight / 2;
          float halfscreenwidth = screenwidth / 2;
          it
            .image(
              halfscreenwidth, 
              halfscreenheight -20,
              (id(play_switch_${my_name}).state == "paused") ? id(play_icon_${my_name}) : id(pause_icon_${my_name}),
              ImageAlign::CENTER,
              (id(play_switch_${my_name}).state == "paused") ? id(my_yellow) : id(my_light_blue));

          it.printf(halfscreenwidth, halfscreenheight +30, id(roboto30), TextAlign::TOP_CENTER, "${my_name}", ${my_name}, id(white));
          it.printf(halfscreenwidth, halfscreenheight +65, id(roboto30), TextAlign::TOP_CENTER, "%2.0f", id(new_volume_${my_name}).state > 0 ? id(new_volume_${my_name}).state : 0 , id(white));